version: 0.2

# This buildspec is intended to be run by CodePipeline builds.

phases:
  install:
    runtime-versions:
      nodejs: 14  
    commands:
      # Install yarn if it wasn't already present in the build instance
      - yarn --version || npm -g install yarn
      
  pre_build:
    commands:
      - echo "Running Pre Build"

  build:
    commands:
      - echo "Running SST Build Stage"
      - cd ./frontend && yarn && cd ..
      - yarn
      - ls -la
      - echo "Executing Yarn Build"
      - yarn sst test
      - yarn sst build --stage aws-BRD-JIRA-22 --region eu-west-2 --verbose

  post_build:
    commands:
      - echo "Running post build and tests"
      - yarn
      - ls -la
      - echo "Executing Yarn Deploy"
      - yarn sst deploy --stage aws-BRD-JIRA-22 --region eu-west-2 --verbose
      #- yarn sst remove --stage aws-BRD-JIRA-22 --region eu-west-2 --verbose
      
      
