version: 0.2

# This buildspec is intended to be run by CodePipeline builds.

phases:
  install:
    runtime-versions:
      nodejs: 14  
    commands:
      # Install yarn if it wasn't already present in the build instance
      - yarn --version || npm -g install yarn
      - apt-get install -y git
      
  pre_build:
    commands:
      - echo "new line"
      - echo "Running Pre Build"
      # Derive all of the neccessary variables to pass for stage name and rollbacks
      - echo Branch Name is $CODEBUILD_SOURCE_VERSION
      - githubRepoName=$(echo $CODEBUILD_SOURCE_REPO_URL|sed 's|.*/||')
      - buildProjectName=$(echo $CODEBUILD_BUILD_ARN |sed 's|.*/||' | sed 's/:.*//')
      - echo GitHub repo name is $githubRepoName
      - echo GitHub source version is $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Build project name is $buildProjectName
      - echo Build ID is $CODEBUILD_BUILD_ID
      - git checkout $CODEBUILD_RESOLVED_SOURCE_VERSION
      - export CODEBUILD_GIT_BRANCH_NAME=`git symbolic-ref HEAD --short | sed -n 's/.*\(BRD-[0-9]*\).*/\1/p'`
      - echo PRINTING OUT THE BRANCH NAME 
      - echo BRANCH NAME IS $CODEBUILD_GIT_BRANCH_NAME
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      

  build:
    commands:
      - echo "Running SST Build Stage"
      - cd ./frontend && yarn && cd ..
      - yarn
      - ls -la
      - echo "Executing Yarn Build"
      - yarn sst test
      - echo PRINTING CURRENT DIR
      - ls -la
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - export CODEBUILD_GIT_BRANCH_NAME=`git symbolic-ref HEAD --short | sed -n 's/.*\(BRD-[0-9]*\).*/\1/p'`
      - echo PRINTING OUT THE BRANCH NAME 
      - echo BRANCH NAME IS $CODEBUILD_GIT_BRANCH_NAME
      - yarn sst build --stage $CODEBUILD_GIT_BRANCH_NAME --region eu-west-2 --verbose

  post_build:
    commands:
      - echo "Running post build and tests"
      - yarn
      - ls -la
      - echo "Executing Yarn Deploy"
      - echo BRANCH NAME IS $CODEBUILD_GIT_BRANCH
      # - yarn sst deploy --stage $CODEBUILD_GIT_BRANCH_NAME --region eu-west-2 --verbose
      # - yarn sst remove --stage $CODEBUILD_GIT_BRANCH_NAME --region eu-west-2 --verbose
      
