version: 0.2

# This buildspec is intended to be run by CodePipeline builds.

env:
  secrets-manager:
    LOGIN: tfgm-br-sonarcloud-keys:sonartoken
    HOST: tfgm-br-sonarcloud-keys:HOST
    Organization: tfgm-br-sonarcloud-keys:Organization
    Project: tfgm-br-sonarcloud-keys:Project

phases:
  install:
    commands:
      # Install yarn if it wasn't already present in the build instance
      - echo "Installing yarn"
      - yarn --version || npm -g install yarn
      - apt-get update
      - apt-get install -y jq
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
  
  pre_build:
    #run-as: Linux-user-name
    #on-failure: ABORT | CONTINUE
    commands:
      - echo "Running pre-build"
      - yarn
      - yarn test
    #finally:
      #- command
      #- command
  
  build:
    commands:
      - echo "Running build"
      - cd ./frontend && yarn
      #- yarn sst build --stage aws-dev --region eu-west-2 --verbose
      
      
  post_build:
    commands:
      - echo "Running post build and tests"
