version: 0.2

# This buildspec is intended to be run by CodePipeline Feature Branch Builds

phases:
  install:
    runtime-versions:
      nodejs: 14  
    commands:
      # Install yarn if it wasn't already present in the build instance
      - apt-get install -y git
      - yarn --version || npm -g install yarn
      - TAG=$(echo "This is test")
      - export FEATURE_BRANCH_NAME
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_HEAD_REF | sed -n 's/.*\(BRD-[0-9]*\).*/\1/p'
      - echo $CODEBUILD_WEBHOOK_HEAD_REF | sed -n 's/.*\(BRD-[0-9]*\).*/\1/p' >> $FEATURE_BRANCH_NAME
      - echo $FEATURE_BRANCH_NAME
     
  pre_build:
    commands:
      - echo "Running Git Checkout Feature"
      - echo "Printing out CodeBuild Source Directory"
      - echo Branch Name is $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $FEATURE_BRANCH_NAME
      #- git log | head -100
      - git status
      - git branch -a
      - echo "End of PreBuild"
      - echo $TAG
      
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on $TAG
      - echo "Running Build Stage"
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      #- export FEATURE_STAGE_NAME=$CODEBUILD_WEBHOOK_HEAD_REF | sed -n 's/.*\(BRD-[0-9]*\).*/\1/p'
      #- echo "${FEATURE_STAGE}" | sed -n 's/.*\(BRD-[0-9]*\).*/\1/p'
      #- echo "Running SST Build Stage"
      #- cd ./frontend && yarn && cd ..
      #- yarn
      #- yarn sst test
      #- yarn sst build --stage $CODEBUILD_GIT_BRANCH_NAME --region eu-west-2 --verbose
      

  post_build:
    commands:
      - echo "Running post build"
