version: 0.2

# This buildspec is intended to be run by CodePipeline Feature Branch Builds

phases:
  install:
    commands:
      # Install yarn if it wasn't already present in the build instance
      - apt-get install -y git
      
  pre_build:
    commands:
      - echo "Running Git Checkout Feature"
      - echo "Printing out CodeBuild Source Directory"
      - echo Branch Name is $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - cd $CODEBUILD_SRC_DIR
      - pwd
      - ls -la 
      - git branch -a
      - echo ""
      
      
      
  build:
    commands:
      - echo "Running Build Stage"
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_HEAD_REF 
      - export FEATURE_STAGE = $CODEBUILD_WEBHOOK_HEAD_REF | sed -n 's/.*\(BRD-[0-9]*\).*/\1/p'
      - echo $FEATURE_STAGE

  post_build:
    commands:
      - echo "Running post build"
