version: 0.2

# This buildspec is intended to be run by CodePipeline Feature Branch Builds
phases:
  install:
    commands:
      # Install yarn if it wasn't already present in the build instance
      - yum install -y git
      
  pre_build:
    commands:
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $AWS_REGION
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_REPO_URL

  build:
    commands:
      - echo "Running Build Stage"
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - git branch -a
      - git log
      - pwd
      - ls -la
      - git switch main
      - git log main --merges --oneline
      - git log --merges --first-parent main --pretty=format:"%h %<(10,trunc)%aN %C(white)%<(15)%ar%Creset %C(red bold)%<(15)%D%Creset %s"
  post_build:
    commands:
      - echo "Running post build"
